<a href="https://colab.research.google.com/github/TGJAISAI/ML-/blob/main/ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [284]:
import pandas as pd 
import numpy

In [285]:
# ML Packages
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction import DictVectorizer

In [286]:
df =  pd.read_csv("/content/india m or f.csv", encoding = "ISO-8859-1")
df.head()

name  gender    race
0          barjraj       1  indian
1     ramdin verma       1  indian
2  sharat chandran       1  indian
3  birender mandal       1  indian
4             amit       1  indian

In [288]:
df = df.dropna()
df.isnull().sum()

name      0
gender    0
race      0
dtype: int64

In [87]:
df[df.gender == 0].shape

(15351, 3)

In [88]:
df[df.gender == 1].shape

(14776, 3)

In [228]:
Xfeatures = df['name']

In [229]:
cv = CountVectorizer()
X = cv.fit_transform(Xfeatures)

In [230]:
from sklearn.model_selection import train_test_split
# Features 
X
# Labels
y = df.gender

In [231]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [232]:
# Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.9131965399316033

In [269]:
# Female is 0, Male is 1
name =  ["atharv"]
vect = cv.transform(name).toarray()
clf.predict(vect)

array([0])

In [233]:
print("Accuracy of Model",clf.score(X_test,y_test)*100,"%")

Accuracy of Model 91.31965399316033 %


In [102]:
# Female is 0, Male is 1
name =  ["ram"]
vect = cv.transform(name).toarray()
clf.predict(vect)

array([1])

In [58]:
sample_name3 = ['aunrag', 'nikhil garakapati', 'sahil', 'dimple','athira','jasmine', 'nidhi']
vect3 = cv.transform(sample_name3).toarray()
clf.predict(vect3)

array([0, 1, 1, 0, 0, 0, 0, 0])

*DecisionTreeClassifier*

In [122]:
Xx_train, Xx_test, yy_train, yy_test = train_test_split(X, y, test_size=0.33,  random_state=42)

In [123]:
from sklearn.tree import DecisionTreeClassifier
 
dclf = DecisionTreeClassifier()
dclf.fit(Xx_train, yy_train)
dclf.score(Xx_test,yy_test)

0.8940856970428486

In [124]:
print("Accuracy of Model",dclf.score(Xx_test,yy_test)*100,"%")

Accuracy of Model 89.40856970428486 %


In [125]:
# Female is 0, Male is 1
sample_name2 = ["kumar"]
vect2 = cv.transform(sample_name2).toarray()
dclf.predict(vect2)

array([1])